name: Lint

on:
  pull_request: {}

env:
  GOPRIVATE: github.com/weaveworks/aws-sdk-go-private

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: weaveworks/eksctl-build:1aa8d27cbafbe5fbea0b0d26d8be3e5984e172af
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache go-build and mod
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build/
            ~/go/pkg/mod/
          key: go-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-
      - name: Lint
        run: make lint
